server:
  address: ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level: "all"
  stdout: true

database:
  default:
    link: "mysql:root:123456@tcp(127.0.0.1:3306)/sakuragf"
    debug: true

gToken:
  CacheMode: 1 #缓存模式 1 gcache 2 gredis
  CacheKey: "GToken:"
  Timeout: 604800000 #7天 部署使用3个小时 10800000
  EncryptKey: "koi29a83idakguqjq29asd9asd8a7jhq"
  MultiLogin: true  #后台是否允许多端同时在线
  LoginPath: /login
  LogoutPath: /logout
  AuthExcludePaths: ['/login'] #校验的路径

# 日志记录回调钩子
operationLog:
  pathMode: 1 #路径记录模式 1 includePath 2 excludePath
  unAuthLog: false #是否记录未登录用户的操作日志
  includePath: ['/admin/sysUser/*']
  excludePath: []

# 鉴权配置，需要鉴权的api路由都要加到sys_auth表，一旦将对应api加入到sys_auth都需要鉴权
authentication:
  superAdminIds: [0] # 配置超级管理员id列表，如果是超级管理直接跳过鉴权


# Redis数据库配置
redis:
  token  :
    address: 106.15.180.144:6379
    db: 0
    pass: 123456
    idleTimeout: 600
  cache  :
    address: 106.15.180.144:6379
    db: 1
    pass: 123456
    idleTimeout: 600
  default:
    address: 106.15.180.144:6379
    db: 2
    pass: 123456
    idleTimeout: 600
