// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysDictType is the golang structure for table sys_dict_type.
type SysDictType struct {
	Id        uint64      `json:"id"        ` //
	DictName  string      `json:"dictName"  ` // 字典中文名
	DictType  string      `json:"dictType"  ` // 字典类型(英文名)
	Status    int         `json:"status"    ` // 状态(1:正常,0:关闭)
	Desc      string      `json:"desc"      ` // 描述
	CreatedAt *gtime.Time `json:"createdAt" ` // 创建时间
	UpdatedAt *gtime.Time `json:"updatedAt" ` // 更新时间
	DeletedAt *gtime.Time `json:"deletedAt" ` // 删除时间
}
