// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysDept is the golang structure for table sys_dept.
type SysDept struct {
	Id        uint        `json:"id"        ` //
	ParentId  uint        `json:"parentId"  ` // 父级id，0代表根
	DeptName  string      `json:"deptName"  ` // 部门名称
	Order     int         `json:"order"     ` // 显示顺序
	Status    int         `json:"status"    ` // 部门状态（1正常，0停用）
	Remark    string      `json:"remark"    ` // 备注
	CreatedAt *gtime.Time `json:"createdAt" ` // 创建时间
	UpdatedAt *gtime.Time `json:"updatedAt" ` // 更新时间
	DeletedAt *gtime.Time `json:"deletedAt" ` // 删除时间
}
