// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysDictData is the golang structure for table sys_dict_data.
type SysDictData struct {
	Id        uint64      `json:"id"        ` //
	Sort      int         `json:"sort"      ` // 排序标记
	Value     int64       `json:"value"     ` // 字典值
	Label     string      `json:"label"     ` // 展示值
	Status    int         `json:"status"    ` // 状态(1:正常,0:禁用)
	TypeId    int64       `json:"typeId"    ` // 字典类型主键
	CreatedAt *gtime.Time `json:"createdAt" ` // 创建时间
	UpdatedAt *gtime.Time `json:"updatedAt" ` // 更新时间
	DeletedAt *gtime.Time `json:"deletedAt" ` // 删除时间
}
