// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysUser is the golang structure for table sys_user.
type SysUser struct {
	Id            uint64      `json:"id"            ` // 主键
	Username      string      `json:"username"      ` // 用户登录账号
	Password      string      `json:"password"      ` // 用户登录密码
	Salt          string      `json:"salt"          ` // 加密盐
	Nickname      string      `json:"nickname"      ` // 用户昵称
	Phone         string      `json:"phone"         ` // 中国手机不带国家代码，国际手机号格式为：国家代码-手机号
	Address       string      `json:"address"       ` // 联系地址
	Email         string      `json:"email"         ` // 用户登录邮箱
	Avatar        string      `json:"avatar"        ` // 用户头像
	Sex           int         `json:"sex"           ` // 性别(0:保密,1:男,2:女)
	DeptId        int64       `json:"deptId"        ` // 部门id
	Remark        string      `json:"remark"        ` // 备注
	LastLoginIp   string      `json:"lastLoginIp"   ` // 最后登录ip
	LastLoginTime *gtime.Time `json:"lastLoginTime" ` // 最后登录时间
	ThemeSetting  string      `json:"themeSetting"  ` // 界面设置
	Status        int         `json:"status"        ` // 用户状态;0:禁用,1:正常,2:未验证
	CreatedAt     *gtime.Time `json:"createdAt"     ` // 创建时间
	UpdatedAt     *gtime.Time `json:"updatedAt"     ` // 更新时间
	DeletedAt     *gtime.Time `json:"deletedAt"     ` // 删除时间
}
