// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysFile is the golang structure for table sys_file.
type SysFile struct {
	Id         uint64      `json:"id"         ` //
	FilePath   string      `json:"filePath"   ` // 文件目录地址
	FileName   string      `json:"fileName"   ` // 文件名
	FileSizeKb int64       `json:"fileSizeKb" ` // 文件大小kb
	FileSuffix string      `json:"fileSuffix" ` // 文件后缀
	CreatedAt  *gtime.Time `json:"createdAt"  ` // 创建时间
	DeletedAt  *gtime.Time `json:"deletedAt"  ` // 删除时间
}
