// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SysAuth is the golang structure of table sys_auth for DAO operations like Where/Data.
type SysAuth struct {
	g.Meta    `orm:"table:sys_auth, do:true"`
	Id        interface{} //
	ParentId  interface{} // 父菜单id
	Type      interface{} // 类型（0目录 1多层目录中间层 2页面 3API 4按钮）
	Title     interface{} // 中文展示名
	RoutePath interface{} // 路由目录(唯一)
	RouteName interface{} // 路由name(唯一)
	ApiPath   interface{} // api路径(唯一)
	BtnName   interface{} // 按钮名称(英文，唯一)
	Icon      interface{} // 菜单icon
	Sort      interface{} // 排序
	Hidden    interface{} // 是否在菜单隐藏（0否 1是）
	Status    interface{} // 状态(1可用 0不可用)
	CreatedAt *gtime.Time // 创建时间
	UpdatedAt *gtime.Time // 更新时间
	DeletedAt *gtime.Time // 删除时间
}
