// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SysOpLog is the golang structure of table sys_op_log for DAO operations like Where/Data.
type SysOpLog struct {
	g.Meta       `orm:"table:sys_op_log, do:true"`
	Id           interface{} //
	UserId       interface{} // 用户id
	Ip           interface{} // 请求ip
	Path         interface{} // 请求路径
	Method       interface{} // 请求方法
	Status       interface{} // 是否正常(0正常 1错误)
	Request      interface{} // 请求body
	Response     interface{} // 响应Body
	ErrorMessage interface{} // 错误信息
	CreatedAt    *gtime.Time // 创建时间
}
