// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// SysOpLogDao is the data access object for table sys_op_log.
type SysOpLogDao struct {
	table   string          // table is the underlying table name of the DAO.
	group   string          // group is the database configuration group name of current DAO.
	columns SysOpLogColumns // columns contains all the column names of Table for convenient usage.
}

// SysOpLogColumns defines and stores column names for table sys_op_log.
type SysOpLogColumns struct {
	Id           string //
	UserId       string // 用户id
	Ip           string // 请求ip
	Path         string // 请求路径
	Method       string // 请求方法
	Status       string // 是否正常(0正常 1错误)
	Request      string // 请求body
	Response     string // 响应Body
	ErrorMessage string // 错误信息
	CreatedAt    string // 创建时间
}

//  sysOpLogColumns holds the columns for table sys_op_log.
var sysOpLogColumns = SysOpLogColumns{
	Id:           "id",
	UserId:       "user_id",
	Ip:           "ip",
	Path:         "path",
	Method:       "method",
	Status:       "status",
	Request:      "request",
	Response:     "response",
	ErrorMessage: "error_message",
	CreatedAt:    "created_at",
}

// NewSysOpLogDao creates and returns a new DAO object for table data access.
func NewSysOpLogDao() *SysOpLogDao {
	return &SysOpLogDao{
		group:   "default",
		table:   "sys_op_log",
		columns: sysOpLogColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *SysOpLogDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *SysOpLogDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *SysOpLogDao) Columns() SysOpLogColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *SysOpLogDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *SysOpLogDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *SysOpLogDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
